### PR TITLE
Use function=FX_DAILY in Finance::Quote::CurrencyRates::AlphaVantage (Fix #229)

### LINKED ISSUE #229: AlphaVantage.co function CURRENCY_EXCHANGE_RATE no longer accepts free API keys.
I use Finance::Quote via GnuCash. Sometime after 1. August 2022, foreign exchange lookups started failing. 

It appears that Finance::Quote uses the CURRENCY_EXCHANGE_RATE function of the AlphaVantage API. Source: [lib/Finance/Quote/CurrencyRates/AlphaVantage.pm#L56](https://github.com/finance-quote/finance-quote/blob/0cfaced5ca98e7cd01ede237a73d3a70f40e2403/lib/Finance/Quote/CurrencyRates/AlphaVantage.pm#L56). 

Looking at the AlphaVantage API documentation, I see that the [CURRENCY_EXCHANGE_RATE function](https://www.alphavantage.co/documentation/#currency-exchange) is (now) marked "Premium", but the [FX_DAILY function](https://www.alphavantage.co/documentation/#fx-daily) is not.

I just tried using both endpoints, using my free API key. I got an error message for CURRENCY_EXCHANGE_RATE, but I got a response for FX_DAILY. See below.

Now while CURRENCY_EXCHANGE_RATE returns near-real-time data, FX_DAILY returns the most recent 100 days at minimum, and can return more.  That works fine for me as a GnuCash user. Could Finance::Quote and GnuCash switch to using FX_DAILY? I would be delighted if one call to Get Quotes in GnuCash gave me 100 days of exchange rate history!

This issue is the subject of [GnuCash bug 798599](https://bugs.gnucash.org/show_bug.cgi?id=798599). There is discussion of this issue on the [GnuCash-user email list, in thread "Online Currency Exchange Rates"](https://lists.gnucash.org/pipermail/gnucash-user/2022-August/102424.html).

Example of exercising the AlphaVantage API functions with a free API key (elided here):
```
% curl "https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_symbol=EUR&to_symbol=USD&apikey=elided"
{
    "Information": "Thank you for using Alpha Vantage! This is a premium endpoint. You may subscribe to any of the premium 
    plans at https://www.alphavantage.co/premium/ to instantly unlock all premium endpoints"
}
% curl "https://www.alphavantage.co/query?function=FX_DAILY&from_symbol=EUR&to_symbol=USD&apikey=elided"
{
    "Meta Data": {
        "1. Information": "Forex Daily Prices (open, high, low, close)",
        "2. From Symbol": "EUR",
        "3. To Symbol": "USD",
        "4. Output Size": "Compact",
        "5. Last Refreshed": "2022-08-15 03:00:00",
        "6. Time Zone": "UTC"
    },
    "Time Series FX (Daily)": {
        "2022-08-15": {
            "1. open": "1.02570",
            "2. high": "1.02683",
            "3. low": "1.02380",
            "4. close": "1.02470"
        },
        "2022-08-14": {

…[elided]…

        },
        "2022-03-28": {
            "1. open": "1.09938",
            "2. high": "1.11363",
            "3. low": "1.09705",
            "4. close": "1.09938"
        }
    }
}
```

### PR DESCRIPTION
**Pull request by shirayu**
AlphaVantage API [CURRENCY_EXCHANGE_RATE](https://www.alphavantage.co/documentation/#currency-exchange) seems to be available only to premium users.
This pull request is to change the code so that they can get the value even if they are not a premium user.

(Fix #229)

### CODE REVIEW

**Comment by JDLH** [comment]
Thank you @shirayu ! I will try to test this in place within GnuCash in the next 24 hours.

**Comment by tjend** [comment]
I have hacked my AlphaVantage.pm file on disk and can confirm I have working exchange rates again after 4 days of failures.

**Comment by JDLH** [comment]
I have checked this patch from within Perl on macOS, and within GnuCash 4.10. It seems to work correctly. Thank you!

My test method was to replace `/Library/Perl/5.30/Finance/Quote/CurrencyRates/AlphaVantage.pm` with the file in this PR. Then I ran a test shell command as shown below, with success as shown below. And, I used the GnuCash -- Price Database -- Update Quotes feature. It succeeded, as measured by 15 August quotes appearing in the price database, and the error alert box not appearing. 

```
% ALPHAVANTAGE_API_KEY=redacted /Applications/Gnucash.app/Contents/Resources/bin/gnc-fq-dump currency USD CAD
1 USD = 1.29193 CAD
``` 

(Before fix, result was this:)
```
Use of uninitialized value $rate in addition (+) at /Library/Perl/5.30/Finance/Quote/CurrencyRates/AlphaVantage.pm line 82.
Use of uninitialized value $rate in addition (+) at /Library/Perl/5.30/Finance/Quote/CurrencyRates/AlphaVantage.pm line 82.
1 USD = <unknown> CAD
```

**Comment by talliberman** [comment]
I tested this fix on Windows with:
```
GnuCash Version: 4.8
Build ID: 4.8a+(2021-09-28)
Finance::Quote: 1.52
```
I replaced `C:\Strawberry\perl\site\lib\Finance\Quote\CurrencyRates` with the file I downloaded [here](https://raw.githubusercontent.com/shirayu/finance-quote/9aee4b6d06da8a0e689b751d0e926160fb99d71b/lib/Finance/Quote/CurrencyRates/AlphaVantage.pm)

It seems to have solved the problem.

Thanks @shirayu

**Comment by N0ury** [comment]
Hi,

Just tried it too on MacOS Big Sur (V11.6.8)
Gnucash Version: 4.11
ID de build: 4.11+(2022-06-25)
Finance::Quote: 1.52

Everything is ok now. Thanks!

**Comment by nomis** [comment]
This fix is incomplete because you need to return the date of the quote too. It's no longer realtime data.

**Comment by shirayu** [comment]
Important point and I agree with it.
I also think that we should continue to use the existing API for premium users.

However, I do not know how to make the changes and cannot take the time needed to investigate.
I would like someone who is familiar with this module to make the rest of the fixes.

**Comment by nomis** [comment]
AlphaVantage is already configured by the environment variable `ALPHAVANTAGE_API_KEY` so I'd add a new one to indicate what service is provided. There doesn't appear to be an API to find out if you have premium access.

**Comment by nomis** [comment]
The data for `FX_DAILY` from AlphaVantage is in fact updated in near-realtime... so the "close" value for today just keeps changing.

For GnuCash price purposes, it would be best to know what date Finance::Quote has obtained in case the data is stale instead of making an assumption, but the API for `currency()` doesn't have any means of doing that.

Your code may not work on weekends. It assumes the "Last Refreshed" date will have exchange rate values but there won't be any for the weekend. Until Saturday it won't be possible to know if "Last Refreshed" will stop on Friday or continue.

File: lib/Finance/Quote/CurrencyRates/AlphaVantage.pm [hunk 1]
```diff
@@ -78,12 +78,13 @@ sub multipliers
     sleep (20) if (($try_cnt < 5) && ($json_data->{'Note'}));
   } while (($try_cnt < 5) && ($json_data->{'Note'}));
 
-  if( !$json_data->{'Realtime Currency Exchange Rate'} ) {
+  if( !$json_data->{'Time Series FX (Daily)'} ) {
     ### No data in JSON
 	  $rate = 0.0;
   } else {
+  my $target = substr($json_data->{'Meta Data'}->{'5. Last Refreshed'}, 0, 10);
```
Comment (nomis) [inline lib/Finance/Quote/CurrencyRates/AlphaVantage.pm:85]:
```
use List::Util qw( maxstr );
```
```suggestion
  my $target = maxstr(keys %{$json_data->{'Time Series FX (Daily)'}});
```

Comment (N0ury) [reply lib/Finance/Quote/CurrencyRates/AlphaVantage.pm:85]: This doesn't work for me. No result from `maxstr(keys %{$json_data->{'Time Series FX (Daily)'}})`

Comment (N0ury) [reply lib/Finance/Quote/CurrencyRates/AlphaVantage.pm:85]: Why not `my $target = (sort { $b cmp $a } keys %{ $json_data->{'Time Series FX (Daily)'} } )[0];`
I'm NOT a perl dev. I've just found similar question question on [stackoverflow](https://stackoverflow.com/questions/47916191/decode-json-and-return-first-key-in-hash)

**Comment by bpschuck** [comment]
FYI - I am still unavailable due to a family medical emergency.

**Comment by dthul** [comment]
Not immediately related to fixing this ticket, but possibly of interest to anyone stumbling across this issue like me:
AlphaVantage currently hands out special free API keys that have the 500 requests/day limit removed and all premium API endpoints enabled (see https://www.alphavantage.co/support/#api-key). I got one of those keys and GnuCash works again :)

**Comment by N0ury** [comment]
Le 2022-09-04 01:46, Daniel Thul a écrit :
> Not immediately related to fixing this ticket, but possibly of interest to anyone stumbling across this issue like me:
> AlphaVantage currently hands out special free API keys that have the 500 requests/day limit removed and all premium API endpoints enabled (see https://www.alphavantage.co/support/#api-key). I got one of those keys and GnuCash works again :)
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/finance-quote/finance-quote/pull/230#issuecomment-1236290862
> You are receiving this because you commented.
> 
> Message ID: ***@***.***>

Thanks for this information.
Is this true for new keys only?
I've tried to get one, but I've been told I already have one.

**Comment by dthul** [comment]
I don't want to spam this issue with unrelated information, so please feel free to delete my post if you feel it is too off topic. But here goes:

<details>
  <summary>Steps to obtain special API key</summary>
> Is this true for new keys only? I've tried to get one, but I've been told I already have one.

It's a new key, yes. I have two now, my old "normal" one and the new "special" one. As indicated in the purple outlined box on AlphaVantage's API key page (https://www.alphavantage.co/support/#api-key), you need to sign up for the Alpha Tournament (https://www.alphatournament.com/) to get one of those special keys, you can't just request it like the "normal" API key.
It's a bit involved, especially if you are not familiar with crypto. Basically you need to connect to your MetaMask wallet on the Alpha Tournament's dashboard page, and your wallet needs to hold some AVC coins (a coin created by AlphaVantage). Then you can claim your special key on the Alpha Torunament's dashboard page.
What I did was the following:
* Sign up for the Alpha Tournament (https://www.alphatournament.com/)
* Install MetaMask (a browser extension) and create a new personal crypto wallet (https://metamask.io/)
* Buy some Ethereum (ETH) or transfer some ETH you already own to your MetaMask wallet. $10 worth of ETH should more than suffice.
* Trade some of those ETH for AVC coins (for example here: https://info.uniswap.org/#/pools/0x08c119404dddcce48182441fd1316ba02b2731ec). For simplicity I just got 100 AVC, but I think less would work too.
* Connect to your MetaMask wallet on the Alpha Tournament's dashboard page
* Once your MetaMask wallet holds some AVC and is connected on the Tournament's dashboard, you can get your special API key on the same page. Most importantly, you don't actually have to participate in the tournament for any of those steps.
</details>

**Comment by hsien-huan** [comment]
I test this new function FX_DAILY but it seems not work for XAU, here is output for reference --
C:\Program Files (x86)\gnucash\bin>perl gnc-fq-dump -v currency USD EUR
1 USD = 1.001 EUR

C:\Program Files (x86)\gnucash\bin>perl gnc-fq-dump -v currency XAU USD
1 XAU = <unknown> USD

Does this means additional function needed for currency gold / silver and so on?

**Comment by bpschuck** [comment]
@dthul and @shirayu,

Someone should probably send a message to guncash-users@lists.gnucash.org inquiring how many users would go through the steps necessary in order to get the special tournament related premium API key.

As someone who always looks at planning for the worse case scenario, I'm also cautious of those keys no longer working if the tournaments were discontinued.

**Comment by JDLH** [comment]
> Someone should probably send a message to [guncash-users@lists.gnucash.org](mailto:guncash-users@lists.gnucash.org) inquiring how many users would go through the steps necessary in order to get the special tournament related premium API key.

Someone could certainly do that, but I do not see how the answer would affect the handling of this issue. I am pretty confident that the response from the GnuCash-user community will be: some get the premium key, some (including me) will not. Plus, GnuCash is not the only consumer of Finance::Quote; what do the other consumers think? 

As long as some consumers will not switch to the premium keys, I think we should continue with the proposed change to using the still-free API.

**Comment by BuongiornoTexas** [comment]
> some get the premium key, some (including me) will not

I know it's annoying to +1, but very much so in this case! I (and I suspect many others) do not want to engage with crypto in any form, and so would not consider this path to a premium key.
